Move past session
src-d/reading-club pull request #74
Opened 2019-07-18 21:31 UTC by bzz

2019-07-18 21:50 UTC, m09 requested changes
Thanks for the admin @bzz :pray: :rocket:

2019-07-18 21:50 UTC, m09 commented on README.md
> +- __2019.07.12__ at __4PM CET__: TBD in [src-d/reading-club#71](https://github.com/src-d/reading-club/issues/71)
```suggestion
- __2019.07.26__ at __4PM CET__: TBD in [src-d/reading-club#71](https://github.com/src-d/reading-club/issues/71)
```

2019-07-19 10:54 UTC, bzz commented
@m09 thank you for catching a date copy-paste! 🙇 

Ready to be merged now.

2019-07-19 11:03 UTC, m09 approved these changes

2019-07-19 12:25 UTC, merged